spring:
  application:
    name: eureka-server
#开启权限认证
  security:
    basic:
      enabled: true
    user:
      name: root
      password: root

server:
  host: localhost
  port: 8761
eureka:
  client:
    #此项目不作为客户端注册
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #开启权限验证后Eureka地址为 用户名：密码@地址：端口号，如未开启权限验证则直接使用 地址：端口号
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${server.host}:${server.port}/eureka



